version: '3'
services:
  ghost:
    image: ghost:1-alpine
    environment:
      - database__client=mysql
      - database__connection__database=ghost
      - database__connection__host=db
      - database__connection__user=root
      - database__connection__password=db
    depends_on:
      - db
    ports:
      - 2368:2368
    networks:
      - mynetwork
    restart: always

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=db
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mynetwork
    restart: always
volumes:
  db-data:
networks:
  mynetwork:
